### ISSUE TITLE
Reading xls file with a variable that has strings and decimal numeric

### ISSUE THREAD

**Issue by vojtech-filipec** [tidyverse/readxl#196] opened 2016-08-17 14:17 UTC
If an XLS has strings and decimal value in one column (variable), the decimal value is round to 6 decimal digits. My file looks like:

PARAMETER   VALUE
lngamma        0.374**0968**
gamma           exp(lngamma)

However, after reading in by read_excel() it looks like

PARAMETER  VALUE
lngamma      0.374**097**
gamma         exp(lngamma)

This is very similar to the issue reported by @quietlyanalysing in [issue 75](https://github.com/hadley/readxl/issues/75)

**Comment by jennybc** [comment] 2017-02-05 01:32
Let's just call this a duplicate of #75 (they will be linked now).

**Closed by jennybc** 2017-02-05 01:32 UTC
