### ISSUE TITLE
xls files not reading correctly into shiny server pro

### ISSUE THREAD

**Issue by rajesh06** [tidyverse/readxl#149] opened 2015-12-04 13:01 UTC
I am using `fileInput` to upload a file into a Shiny App in Shiny Server Pro. (Note - I do not have this problem when running the app locally - it only is an issue with Shiny Server Pro.)

I then use `read_excel` to assign the contents of that file to a dataframe object. Finally, I display the data in the dataframe

[hello_world.xlsx](https://github.com/hadley/readxl/files/52051/hello_world.xlsx)

 using `renderDataTable`

This works fine with xls**x** files but not xls files. The issue with the latter is that column headers and character variables do not display.

Here is the `server.R` code:

```
library(shiny)
library(readxl)

shinyServer(function(input, output) {
  current_data <- reactive({
    inFile <- input$file1
    if (is.null(inFile))
      return(NULL)
    file.rename(inFile$datapath,
     paste(inFile$datapath, ".xls", sep="")) #change to xlsx
    current_data <- read_excel(paste(inFile$datapath, ".xls", sep=""), 1, TRUE) #change to xlsx
  })
  output$my_table <- renderDataTable({current_data()})
})
```

and the `ui.R` code:

```

library(shiny)

shinyUI(fluidPage(

  # Application title
  titlePanel("Readxl Test"),

  # Sidebar with a slider input for number of bins
  sidebarLayout(
    sidebarPanel(
      fileInput('file1', 'Choose Excel file to upload',#,
        accept = c(".xls",".XLS", ".xlsx")
      )
    ),

    # Show a plot of the generated distribution
    mainPanel(
      dataTableOutput("my_table")

    )
  )
))
```

The files I am reading in are identical save for the extension (and presumably some underlying Excel coding differences between xls and xlsx). I of course modify the code of `server.R` for the change in extension.

I have attached the xlsx files for reference. The xls file is not supported but github but if you open the xlsx and save as xls using Excel you should be able to replicate.

**Comment by zross** [comment] 2016-07-18 20:14
Did you find a solution to this? I have not had luck using readxl with Shiny.

**Comment by zross** [comment] 2016-07-18 20:16
Duplicate of #85

**Closed** 2017-02-01 19:57 UTC
