### ISSUE TITLE
Failure to open an ordinary-looking XLS file

### ISSUE THREAD

**Issue by LTLA** [tidyverse/readxl#507] opened 2018-09-19 20:37 UTC
I've been trying to run the code below:

```r
download.file("ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE61nnn/GSE61533/suppl/GSE61533%5FHTSEQ%5Fcount%5Fresults%2Exls%2Egz", 
    "GSE61533_HTSEQ_count_results.xls.gz")
## trying URL 'ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE61nnn/GSE61533/suppl/GSE61533%5FHTSEQ%5Fcount%5Fresults%2Exls%2Egz'
## Content type 'unknown' length 2294628 bytes (2.2 MB)
## ==================================================

library(R.utils)
gunzip("GSE61533_HTSEQ_count_results.xls.gz")

library(readxl)
counts <- read_xls("GSE61533_HTSEQ_count_results.xls")
## Error in read_fun(path = path, sheet_i = sheet, limits = limits, shim = shim,  : 
##  Failed to open GSE61533_HTSEQ_count_results.xls
```

I'm not quite sure what's going wrong here. I'm able to open the XLS file using LibreOffice (on Ubuntu), and with other R-based methods like `gdata::read.xls` so I assume the file itself is fine.

Interestingly, the same code works with much older versions of _readxl_. I've tested 0f5c88e9ab50f5b995c799b28fd7eb4a35f4f382, which works:

```r
library(readxl)
counts <- read_xls("GSE61533_HTSEQ_count_results.xls")
counts[1:10,]
## # A tibble: 10 x 97
##    ID    HSC1_1 HSC1_2 HSC1_3 HSC1_4 HSC1_5 HSC1_6 HSC1_7 HSC1_8 HSC1_9 HSC1_10
##    <chr>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>   <dbl>
##  1 0610…      0      0      0      0      0      0      0      0      0       0
##  2 0610…     25      0    304      0    154    550    117    177    204     241
##  3 0610…      0      0      0      0      0      0      0      0      0       0
##  4 0610…      0      0      0      0      0      0      0      0      0       0
##  5 0610…      0      0      0      8     83    521    236     57    741       0
##  6 0610…    241      0     66     60    356    173    385     64    222     506
##  7 0610…      0      0      0      0     72     83      0      0      0       0
##  8 0610…      0      0      0      0     46      0     82      0      0       0
##  9 0610…      0      0      0      0    209      0     51     24      0     325
## 10 0610…      0      0      0      1      0      0      0      0      0       0
## # ... with 86 more variables: HSC1_11 <dbl>, HSC1_12 <dbl>, HSC1_13 <dbl>,
## #   HSC1_14 <dbl>, HSC1_15 <dbl>, HSC1_16 <dbl>, HSC1_17 <dbl>, HSC1_18 <dbl>,
## #   HSC1_19 <dbl>, HSC1_20 <dbl>, HSC1_21 <dbl>, HSC1_22 <dbl>, HSC1_23 <dbl>,
## #   HSC1_24 <dbl>, HSC1_25 <dbl>, HSC1_26 <dbl>, HSC1_27 <dbl>, HSC1_28 <dbl>,
## #   HSC1_29 <dbl>, HSC1_30 <dbl>, HSC1_31 <dbl>, HSC1_32 <dbl>, HSC1_33 <dbl>,
## #   HSC1_34 <dbl>, HSC1_35 <dbl>, HSC1_36 <dbl>, HSC1_37 <dbl>, HSC1_38 <dbl>,
## #   HSC1_39 <dbl>, HSC1_40 <dbl>, HSC1_41 <dbl>, HSC1_42 <dbl>, HSC1_43 <dbl>,
## #   HSC1_44 <dbl>, HSC1_45 <dbl>, HSC1_46 <dbl>, HSC1_47 <dbl>, HSC1_48 <dbl>,
## #   HSC1_49 <dbl>, HSC1_50 <dbl>, HSC1_51 <dbl>, HSC1_52 <dbl>, HSC1_53 <dbl>,
## #   HSC1_54 <dbl>, HSC1_55 <dbl>, HSC1_56 <dbl>, HSC1_57 <dbl>, HSC1_58 <dbl>,
## #   HSC1_59 <dbl>, HSC1_60 <dbl>, HSC1_61 <dbl>, HSC1_62 <dbl>, HSC1_63 <dbl>,
## #   HSC1_64 <dbl>, HSC1_65 <dbl>, HSC1_66 <dbl>, HSC1_67 <dbl>, HSC1_68 <dbl>,
## #   HSC1_69 <dbl>, HSC1_70 <dbl>, HSC1_71 <dbl>, HSC1_72 <dbl>, HSC1_73 <dbl>,
## #   HSC1_74 <dbl>, HSC1_75 <dbl>, HSC1_76 <dbl>, HSC1_77 <dbl>, HSC1_78 <dbl>,
## #   HSC1_79 <dbl>, HSC1_80 <dbl>, HSC1_81 <dbl>, HSC1_82 <dbl>, HSC1_83 <dbl>,
## #   HSC1_84 <dbl>, HSC1_85 <dbl>, HSC1_86 <dbl>, HSC1_87 <dbl>, HSC1_88 <dbl>,
## #   HSC1_89 <dbl>, HSC1_90 <dbl>, HSC1_91 <dbl>, HSC1_92 <dbl>, HSC1_93 <dbl>,
## #   HSC1_94 <dbl>, HSC1_95 <dbl>, HSC1_96 <dbl>
```

(That was just a randomly chosen commit, I don't know the exact point at which it stopped working.)

<details>
<summary>Session information (for the failing use case)</summary>

```
R version 3.5.0 Patched (2018-04-30 r74679)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /home/cri.camres.org/lun01/Software/R/R-3-5-branch/lib/libRblas.so
LAPACK: /home/cri.camres.org/lun01/Software/R/R-3-5-branch/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readxl_1.1.0      R.utils_2.7.0     R.oo_1.22.0       R.methodsS3_1.7.1

loaded via a namespace (and not attached):
[1] compiler_3.5.0   pillar_1.3.0     tibble_1.4.2     crayon_1.3.4    
[5] Rcpp_0.12.18     cellranger_1.1.0 rlang_0.2.2     
```
</details>

**Comment by cderv** [comment] 2018-09-20 06:13
It is working for me with the dev version of `readxl`
``` r
# use a temp file in temp directory
temp_file <- tempfile(fileext = ".xls.gz")
download.file("ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE61nnn/GSE61533/suppl/GSE61533%5FHTSEQ%5Fcount%5Fresults%2Exls%2Egz", 
              temp_file, mode = "wb")
# decompress file
xls_file <- R.utils::gunzip(temp_file)
# load dev version that is installed in dev lib
# by devtools::install_github("tidyverse/readxl)
devtools::dev_mode(on = TRUE)
#> Dev mode: ON
library(readxl)
packageVersion("readxl")
#> [1] '1.1.0.9000'
counts <- read_xls(xls_file)
str(counts[, 1:5])
#> Classes 'tbl_df', 'tbl' and 'data.frame':    38498 obs. of  5 variables:
#>  $ ID    : chr  "0610005C13Rik" "0610007P14Rik" "0610008F07Rik" "0610009B14Rik" ...
#>  $ HSC1_1: num  0 25 0 0 0 241 0 0 0 0 ...
#>  $ HSC1_2: num  0 0 0 0 0 0 0 0 0 0 ...
#>  $ HSC1_3: num  0 304 0 0 0 66 0 0 0 0 ...
#>  $ HSC1_4: num  0 0 0 0 8 60 0 0 0 1 ...
```

<sup>Created on 2018-09-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Not sure if there was a fix or not. Can you try with the last version ?

**Comment by jennybc** [comment] 2018-09-20 16:50
The embedded libxls library has been getting a lot of "Spring Cleaning" this year. This has been overwhelmingly positive, but there have been some regressions along the way. This looks like a case where the libxls state at the most recent CRAN release was bad for certain xls files, such as this one. And that things have improved in libxls (and readxl) since.

There are no readxl features driving a new release in the near future. But if there was enough evidence of libxls problems that would be fixed by a release I can do that. readxl has quite a lot of reverse dependencies (by my standards but not compared to ggplot2!), so I don't do releases casually.

**Comment by LTLA** [comment] 2018-09-20 17:28
Fair enough. This is the only Excel file for which I've encountered this problem, but then again, I don't deal with Excel files regularly. Hopefully it gets fixed sooner rather than later.

**Comment by jennybc** [comment] 2018-09-20 19:38
I'm going to close this since it is resolved in dev. And I'm well aware of this issue re: the embedded libxls state.

**Closed by jennybc** 2018-09-20 19:38 UTC
