### ISSUE TITLE
Some columns are complety garbled

### ISSUE THREAD

**Issue by joelgombin** [tidyverse/readxl#129] opened 2015-09-12 20:50 UTC
I tried to read [this xls file](http://www.insee.fr/fr/themes/detail.asp?reg_id=99&ref_id=infra-population-07)  in with `read_xls` :

``` r
df <- read_excel("/media/Data/Dropbox/Thèse/Données insee lasmas/RP2007/BTX_IC_POP_2007.xls", skip = 5)
```

It worked, but:
- if you look at the tail of the resulting `tbl_df`, you'll see that (at least on my machine) something went wrong. Some values are in a different column than they should be, others are repeated several times... 

``` r
> tail(df)
Source: local data frame [6 x 100]

       IRIS   REG   DEP UU1999       COM LIBCOM TRIRIS            GRD_QUART          LIBIRIS TYP_IRIS MODIF_IRIS
      (chr) (chr) (chr)  (chr)     (chr)  (chr)  (chr)                (chr)            (chr)    (chr)      (chr)
1     09283    04 08488 Saurat 092810000  09281 ZZZZZZ Savignac-les-Ormeaux        092840000        H         00
2     09284    04 08488 Ségura 092850000  09285 ZZZZZZ                 Seix        092860000        H         00
3     09286    04 08488 Ségura 092850000  09285 ZZZZZZ                 Seix              Sem        H         00
4 092870000    04 08488 Ségura 092850000  09285 ZZZZZZ                 Seix            09287        H         00
5  Senconac    04 08488 Ségura 092850000  09285 ZZZZZZ                 Seix        092890000        H         00
6     09289    04 08488 Ségura 092850000  09285 ZZZZZZ                 Seix Lorp-Sentaraille        D         00
Variables not shown: LAB_IRIS (chr), P07_POP (dbl), P07_POP0002 (dbl), P07_POP0305 (dbl), P07_POP0610 (dbl),
  P07_POP1117 (dbl), P07_POP1824 (dbl), P07_POP2539 (dbl), P07_POP4054 (dbl), P07_POP5564 (dbl), P07_POP6579 (dbl),
  P07_POP80P (dbl), P07_POP0003 (dbl), P07_POP0408 (dbl), P07_POP0913 (dbl), P07_POP1418 (dbl), P07_POP1938 (dbl),
  P07_POP3958 (dbl), P07_POP5973 (dbl), P07_POP74P (dbl), P07_POP0014 (dbl), P07_POP1529 (dbl), P07_POP3044 (dbl),
  P07_POP4559 (dbl), P07_POP6074 (dbl), P07_POP75P (dbl), P07_POP0019 (dbl), P07_POP2064 (dbl), P07_POP65P (dbl),
  P07_POPH (dbl), P07_H0014 (dbl), P07_H1529 (dbl), P07_H3044 (dbl), P07_H4559 (dbl), P07_H6074 (dbl), P07_H75P (dbl),
  P07_H0019 (dbl), P07_H2064 (dbl), P07_H65P (dbl), P07_POPF (dbl), P07_F0014 (dbl), P07_F1529 (dbl), P07_F3044 (dbl),
  P07_F4559 (dbl), P07_F6074 (dbl), P07_F75P (dbl), P07_F0019 (dbl), P07_F2064 (dbl), P07_F65P (dbl), P07_POP05P (dbl),
  P07_POP05P_IRAN1 (dbl), P07_POP05P_IRAN2 (dbl), P07_POP05P_IRAN3 (dbl), P07_POP05P_IRAN4 (dbl), P07_POP05P_IRAN5
  (dbl), P07_POP05P_IRAN6 (dbl), P07_POP05P_IRAN7 (dbl), C07_POP15P (dbl), C07_POP15P_CS1 (dbl), C07_POP15P_CS2 (dbl),
  C07_POP15P_CS3 (dbl), C07_POP15P_CS4 (dbl), C07_POP15P_CS5 (dbl), C07_POP15P_CS6 (dbl), C07_POP15P_CS7 (dbl),
  C07_POP15P_CS8 (dbl), C07_H15P (dbl), C07_H15P_CS1 (dbl), C07_H15P_CS2 (dbl), C07_H15P_CS3 (dbl), C07_H15P_CS4 (dbl),
  C07_H15P_CS5 (dbl), C07_H15P_CS6 (dbl), C07_H15P_CS7 (dbl), C07_H15P_CS8 (dbl), C07_F15P (dbl), C07_F15P_CS1 (dbl),
  C07_F15P_CS2 (dbl), C07_F15P_CS3 (dbl), C07_F15P_CS4 (dbl), C07_F15P_CS5 (dbl), C07_F15P_CS6 (dbl), C07_F15P_CS7
  (dbl), C07_F15P_CS8 (dbl), P07_POP_FR (dbl), P07_POP_ETR (dbl), P07_POP_IMM (dbl), P07_PMEN (dbl), P07_PHORMEN (dbl)
```

The number of rows and columns is correct, though.

Any idea what's going on here?

**Comment by joelgombin** [comment] 2015-09-12 20:51
(BTW, my `sesionInfo()`:

```r
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readxl_0.1.0        dplyr_0.4.3         plyr_1.8.3          spReapportion_0.1.0 rgeos_0.3-12       
[6] maptools_0.8-36     sp_1.2-0           

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.1     lattice_0.20-33 assertthat_0.1  grid_3.2.2      R6_2.1.1        DBI_0.3.1       magrittr_1.5   
 [8] tools_3.2.2     foreign_0.8-66  parallel_3.2.2 
```

**Comment by daxiagithub** [comment] 2015-09-18 16:44
This looks like a very similar issue I reported previously (#128).

**Comment by joelgombin** [comment] 2015-09-18 16:45
Indeed, sorry I hadn't seen it.

**Comment by daxiagithub** [comment] 2015-09-18 16:58
No problem.  It's good the issue has been verified by different people.

**Comment by jennybc** [comment] 2017-02-24 11:38
Assuming a duplicate of #128.

**Comment by jennybc** [comment] 2017-02-24 14:34
I also get a garbled result, but garbled differently from yours @joelgombin 😁. I don't have a diagnosis yet. I note there are many instances of numbers formatted as text, but that could be neither here nor there.

I don't even get the correct column names and my overall impression is that the problem may lie in the string table but that's really a wild guess. If I copy the entire file and resave as xls, that does not help. If I just copy the first ~20 rows, it seems to import correctly.

**Comment by jennybc** [comment] 2017-02-24 14:36
Leaving a few more notes: this file is quite large (82MB) and the first sheet we are all reading has >50K rows and >90 cols.

**Comment by jennybc** [comment] 2017-03-09 17:54
If we're going to close #128, we must reopen this. Because there is something going on with certain xls files. I can reproduce it with a file in this thread, for example.

**Comment by hadley** [comment] 2017-03-09 18:00
Has the website changed? The original url doesn't download an xls anymore.

**Comment by jennybc** [comment] 2017-03-09 18:06
@hadley Yes I eventually figured out which file it was. I think it's this? 

https://www.insee.fr/fr/statistiques/fichier/2028650/BTX_IC_POP_2007.zip

**Comment by joelgombin** [comment] 2017-03-09 18:10
Yes unfortunately they recently completely changed the website and broke
all the urls...

**Comment by hadley** [comment] 2017-03-10 03:19
If I open this doc and re-save it in excel, it seems to open OK.  That suggests it's not going to be possible for us to fix this bug, as it's likely to be in the underlying libxls library.

**Comment by jennybc** [comment] 2017-03-10 16:36
@hadley Yes, for me it opens without error, but on closer inspection, I find the resulting data frame is quite garbled. I plan to do a little "Excel bisect" on it, to see if I can find the Cell of Doom and learn anything.

**Comment by hadley** [comment] 2017-03-10 18:28
@jennybc I don't think you'll be able to do that, because as soon as you resave it (without making any real changes), it loads fine.

**Comment by jennybc** [comment] 2017-03-16 03:40
I've convinced myself this is a bug in libxls. I don't get errors loading the sheet or copies thereof. But upon inspection, the contents have been garbled. The bisect exercise was somewhat informative in that sheets consisting of various subsets of the original xls also import w/o error (but garbled). The cell contents are always contents of *some cell, somewhere in the file*, but often on another worksheet entirely. That makes the bug seem somewhat fixable? But I should probably prioritize problems or features in readxl itself.

**Comment by jennybc** [comment] 2017-03-17 18:00
More evidence that it's libxls: gdata appears to read the contents of this xls correctly (passes my eyeball test). I note it is 10X slower. But correct.

``` r
system.time(xls <- read_excel("iss/BTX_IC_POP_2007.xls", skip = 5))
#>   user  system elapsed 
#> 16.040   0.588  16.712 

system.time(xlsx <- read_excel("iss/BTX_IC_POP_2007.xlsx", skip = 5))
#>   user  system elapsed 
#>  9.489   1.188  10.808 

system.time(gdata <- read.xls("iss/BTX_IC_POP_2007.xls", pattern = "LIBCOM"))
#>    user  system elapsed 
#> 194.464   3.506 198.570 
```

**Comment by joelgombin** [comment] 2017-03-17 18:02
Yes I can confirm this.

**Closed** 2017-03-19 15:07 UTC
Labels: xls
