### ISSUE TITLE
Reading xls written from WriteXLS package loses last column

### ISSUE THREAD

**Issue by carlganz** [tidyverse/readxl#180] opened 2016-06-09 15:28 UTC
Hello,

I have found that if you read an XLS written from the `WriteXLS` package that the right most column is not read in. Here is an example:

``` R
z <- tempdir()
ncol(mtcars) # should be 11
WriteXLS::WriteXLS(mtcars,paste0(z,"/mtcars.xls)
mtcars.xls <- readxl::read_excel(paste0(z,"/mtcars.xls"))
ncol(mtcars.xls) # is 10 for some reason
```

The carb column is not read in even though it exists when you open the excel file. I don't know if this is an issue with `readxl` or `WriteXLS`. Let me know if you need any other information.

Regards

**Comment by carlganz** [comment] 2016-06-09 16:15
It appears after talking to the maintainer of `WriteXLS` marcschwartz/WriteXLS#9 that this is a `readxl` issue

**Comment by jennybc** [comment] 2017-01-19 17:14
This sounds like #152

**Comment by jennybc** [comment] 2017-02-24 11:48
Assuming a duplicate of #128

**Closed by jennybc** 2017-02-24 11:48 UTC
Labels: xls

**Comment by jennybc** [comment] 2017-02-24 15:47
Not a duplicate of #128.
