### ISSUE TITLE
Fail to read a certain xls file.

### ISSUE THREAD

**Issue by KKPMW** [tidyverse/readxl#417] opened 2018-01-18 21:17 UTC
Hello,

Recently I ran into an issue when trying to read a certain xls file using `readxl::read_xls`. It crashes R with segment fault error.

URL to the file:
https://www.seco.admin.ch/dam/seco/de/dokumente/Wirtschaft/Wirtschaftslage/VIP%20Quartalssch%C3%A4tzungen/qna_p_na.xls.download.xls/qna_p_na.xls

Reproducible example showing the behaviour:

```r
url <- paste0("https://www.seco.admin.ch/dam/seco/de/dokumente/Wirtschaft/",
              "Wirtschaftslage/VIP%20Quartalssch%C3%A4tzungen/",
              "qna_p_na.xls.download.xls/qna_p_na.xls")

xlsfile <- tempfile()
download.file(url, xlsfile)
#> trying URL 'https://www.seco.admin.ch/dam/seco/de/dokumente/Wirtschaft/Wirtschaftslage/VIP%20Quartalssch%C3%A4tzungen/qna_p_na.xls.download.xls/qna_p_na.xls'

#> Content type 'application/vnd.ms-excel' length 722944 bytes (706 KB)
#> ==================================================
#> downloaded 706 KB

readxl::read_xls(xlsfile, sheet=1)
#>  *** caught segfault ***
#> address 0x0, cause 'memory not mapped'

#> Traceback:
#> 1: .Call(`_readxl_read_xls_`, path, sheet_i, limits, shim, col_names,     col_types, na, trim_ws, guess_max)
#> 2: read_fun(path = path, sheet_i = sheet, limits = limits, shim = shim,     col_names = col_names, col_types = col_types, na = na, trim_ws = trim_ws,     guess_max = guess_max)
#> 3: tibble::as_tibble(read_fun(path = path, sheet_i = sheet, limits = limits,     shim = shim, col_names = col_names, col_types = col_types,     na = na, trim_ws = trim_ws, guess_max = guess_max), validate = FALSE)
#> 4: tibble::repair_names(tibble::as_tibble(read_fun(path = path,     sheet_i = sheet, limits = limits, shim = shim, col_names = col_names,     col_types = col_types, na = na, trim_ws = trim_ws, guess_max = guess_max),     validate = FALSE), prefix = "X", sep = "__")
#> 5: read_excel_(path = path, sheet = sheet, range = range, col_names = col_names,     col_types = col_types, na = na, skip = skip, n_max = n_max,     guess_max = guess_max, format = "xls")
#> 6: readxl::read_xls(xlsfile, sheet = 1)


#> Possible actions:
#> 1: abort (with core dump, if enabled)
#> 2: normal R exit
#> 3: exit R without saving workspace
#> 4: exit R saving workspace
```

The same behaviour was repeated on all 3 main operating systems: OS X, linux and windows.

File seems to be working when read with `xslx` library.

Other files from the same place work without errors:

```r
library(reprex)

url <- paste0("https://www.seco.admin.ch/dam/seco/de/dokumente/Wirtschaft/",
              "Wirtschaftslage/VIP%20Quartalssch%C3%A4tzungen/",
              "qna_i_na.xls.download.xls/qna_i_na.xls")

xlsfile <- tempfile()
download.file(url, xlsfile)

readxl::read_xls(xlsfile, sheet=1)
```

Any insights or possible solutions are highly appreciated.

And if I can be of any help in tracking down the issue further - please let me know.

**Comment by jennybc** [comment] 2018-01-18 21:30
At this point, all I can say I can reproduce it. Will look into it.

**Comment by jennybc** [comment] 2018-04-15 03:37
I note that all the worksheets appear to be protected. Is that true of the other, related files that you *can* read with readxl?

**Comment by jennybc** [comment] 2018-12-14 03:02
Making a pass through all xls issues.

The current release candidate for readxl embeds libxls as of https://github.com/evanmiller/libxls/commit/b6192a3eb4f5ba99435db259ca1fb442b1e8cba7.

And I still get the same result with readxl and the standalone xls2csv tool.

I've re-reported upstream. If it doesn't resolve this time around, I'm going to close this because it would seem to be an exotic problem that is very unique to this sheet.

**Comment by kiadso** [comment] 2019-01-22 17:33
I am having a similar problem. We are working with a Homeless Management Information Systems (HMIS) software called ServicePoint and this Excel file is exported from this system. The file is not password protected or anything. When I run this code, RStudio crashes. The way I can get it to not crash RStudio is by first opening it, clicking "Enable Editing" and then closing it again.

Here's the code I'm using: `library(readxl)
users <- read_xls("AreasAndCounties.xls", sheet = 1, range = cell_cols("A:F"))`

I tried uploading the file, but it's a .xls and is not supported. I can email you the file.

**Comment by kiadso** [comment] 2019-01-23 15:24
I wanted to update. I upgraded my version of R and now it no longer crashes RStudio, but it also doesn't read the file. Again, I can work around the problem by opening the file and clicking Enable Editing.

**Comment by jennybc** [comment] 2019-01-24 21:58
@kiadso Can you open a new issue for this? I'm about to insert our standard instructions re: how you can share your example, even if it is `.xls`.

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box. `.xlsx` is a supported file type. You'll need to zip or gzip `.xls` so it appears as `.zip` or `.gz`.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by jennybc** [comment] 2019-02-13 04:47
As of libxls v1.5.0, this still is not readable by libxls itself, i.e. it has nothing to do with readxl.

``` bash
jenny@2015-mbp libxls-evanmiller-github $ xls2csv ~/rrr/readxl/investigations/qna_p_na.xls
FILE: /Users/jenny/rrr/readxl/investigations/qna_p_na.xls
Error reading XLS file: Unable to allocate memory
```

I'm going to bring this to a close. Maybe one day it will be readable, but there's nothing to do here in this package.

**Closed by jennybc** 2019-02-13 04:47 UTC
Labels: libxls bug, xls 👵
