### ISSUE TITLE
read_excel reads wrong data

### ISSUE THREAD

**Issue by Waschoi** [tidyverse/readxl#713] opened 2022-10-13 18:50 UTC
Hello,
I experienced the problem today for the first time in productive use and could now reproduce it on a 2nd computer. It also affects openxlsx, so it could be an Excel problem:
![image](https://user-images.githubusercontent.com/34303168/195679896-ababdd3b-23bd-40eb-9958-18fb1a7d9432.png)
gives:
![image](https://user-images.githubusercontent.com/34303168/195679977-0231033c-e71a-4f93-88ab-21ee757472ae.png)
whereas e.g. 5,9 in row 2 gives:
![image](https://user-images.githubusercontent.com/34303168/195680224-1903208c-9bfa-4da4-85a7-ea8c385257ed.png)

I really don't know why this happens, but it was a real problem today, not just a toy example.

R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8   
[3] LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.2.1   magrittr_2.0.3   cli_3.3.0        tools_4.2.1     
 [5] pillar_1.8.1     glue_1.6.2       rstudioapi_0.14  tibble_3.1.8    
 [9] utf8_1.2.2       fansi_1.0.3      cellranger_1.1.0 vctrs_0.4.1     
[13] readxl_1.4.1     lifecycle_1.0.1  pkgconfig_2.0.3  rlang_1.0.4

**Comment by jennybc** [comment] 2022-10-13 23:17
Duplicate of issues such as #423 #673 #525 and the like.

**Closed by jennybc** 2022-10-13 23:17 UTC
