### ISSUE TITLE
no "fill=TRUE" possibility

### ISSUE THREAD

**Issue by jcolomb** [tidyverse/readxl#142] opened 2015-11-02 16:16 UTC
Hi.

I am importing and concenating different excel files obtained from a different software.
I am reading the data skipping the headers with the read_excel function (if I do not do that, the date format is lost, because the headers has multiple lines).

My problem is that one column is often empty, such that it disappear with the read_excel function. I tried fill=TRUE but it is not supported.

thanks for your great job, by the way

**Comment by jennybc** [comment] 2017-01-20 22:35
What exactly do you expect `fill = TRUE` to do?

It sounds like you need to use a row binding function that can handle bind-ees that don't have exactly the same columns. Will you see if `dplyr::bind_rows()` solves your problem?

I'm not sure this is a readxl problem right now. (Well, there are many other issues about headers, row skipping, and blank cols that will lead to improvements that might help you too!)

**Comment by jennybc** [comment] 2017-02-05 00:17
Duplicate of #157

**Closed by jennybc** 2017-02-05 00:17 UTC
