### ISSUE TITLE
read failure

### ISSUE THREAD

**Issue by ajdamico** [tidyverse/readxl#474] opened 2018-04-28 11:20 UTC
hi @jennybc and @evanmiller,  the minimal reproducible example below appears similar to the libxls bugs reported at #471, #417, #391 -- downgrading to `1.0.0` solves the problem.  thanks for the fantastic software

	# works on v1.0.0 but fails on today's dev and also cran
	# devtools::install_github("tidyverse/readxl",ref='v1.0.0')

	
	tf <- tempfile()
	fn <- 'https://www.cms.gov//Medicare/Prescription-Drug-Coverage/PrescriptionDrugCovGenIn/Downloads/2015-Landscape-and-Plan-and-Premium-Files-For-Medicare-Plans-Offering-Part-D-Coverage.zip'
	download.file( fn , tf , mode = 'wb' )
	z <- unzip( tf , exdir = tempdir() )
	y <- unzip( z[2] , exdir = tempdir() )
	x <- readxl::read_excel( y[5] )

**Comment by jennybc** [comment] 2018-04-28 20:12
Confirmed. If we are lucky, these all have the same underlying cause.

**Comment by jennybc** [comment] 2018-04-28 20:33
Sorry for the noise (deleted those comments): I must have been using readxl behind current dev version.

I **can** read this file with current readxl:

``` r
devtools::load_all("~/rrr/readxl")
#> Loading readxl
git2r::sha(git2r::last_commit("~/rrr/readxl"))
#> [1] "66df4b9e65babd7e5b63db2f371fc54d29ef98b8"
packageVersion("readxl")
#> [1] '1.1.0.9000'

tf <- tempfile()
fn <- 'https://www.cms.gov//Medicare/Prescription-Drug-Coverage/PrescriptionDrugCovGenIn/Downloads/2015-Landscape-and-Plan-and-Premium-Files-For-Medicare-Plans-Offering-Part-D-Coverage.zip'
download.file( fn , tf , mode = 'wb' )
z <- unzip( tf , exdir = tempdir() )
y <- unzip( z[2] , exdir = "investigations" )
readxl::read_excel( y[5], skip = 3)
#> # A tibble: 16,662 x 26
#>    State  County  `Organization Na… `Plan Name`    `Contract ID` `Plan ID`
#>    <chr>  <chr>   <chr>             <chr>          <chr>             <dbl>
#>  1 Alaba… (All C… Aetna Medicare    Aetna Medicar… S5810               182
#>  2 Alaba… (All C… Aetna Medicare    Aetna Medicar… S5810                46
#>  3 Alaba… (All C… BlueRx (PDP)      BlueRx Option… S1030                 6
#>  4 Alaba… (All C… BlueRx (PDP)      BlueRx Option… S1030                 1
#>  5 Alaba… (All C… Cigna-HealthSpri… Cigna-HealthS… S5617               220
#>  6 Alaba… (All C… Cigna-HealthSpri… Cigna-HealthS… S5617               182
#>  7 Alaba… (All C… Cigna-HealthSpri… Cigna-HealthS… S5617               257
#>  8 Alaba… (All C… EnvisionRx Plus   EnvisionRxPlu… S7694                12
#>  9 Alaba… (All C… Express Scripts … Express Scrip… S5660               182
#> 10 Alaba… (All C… Express Scripts … Express Scrip… S5660               114
#> # ... with 16,652 more rows, and 20 more variables: `Segment ID` <dbl>,
#> #   `Organization Type` <chr>, `Plan Type` <chr>, `Special Needs
#> #   Plan` <chr>, `Special Needs Plan Type` <chr>, `Benefit Type` <chr>,
#> #   `Part D Basic Premium Below Regional Benchmark?` <chr>, `National
#> #   PDP` <chr>, `Part C Premium2` <dbl>, `Part D Basic Premium3` <dbl>,
#> #   `Part D Supplemental Premium4` <dbl>, `Part D Total Premium5` <dbl>,
#> #   `Part D Premium Obligation with Full Premium Assistance6` <dbl>, `Part
#> #   D Premium Obligation with 75% Premium Assistance` <dbl>, `Part D
#> #   Premium Obligation with 50% Premium Assistance` <dbl>, `Part D Premium
#> #   Obligation with 25% Premium Assistance` <dbl>, `Part D Drug
#> #   Deductible` <dbl>, `Tiers Not Subject to Deductible7` <dbl>,
#> #   `Increased Initial Coverage Limit8` <chr>, `Extra Coverage in
#> #   Gap` <chr>
```

Created on 2018-04-28 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by jennybc** [comment] 2018-04-28 20:35
So this appears to have been fixed in libxls and therefore readxl since the v1.1.0 release.

I am considering making a patch release of readxl, with just the libxls fixes, within the next month, once things shake out a bit more.

**Closed by jennybc** 2018-04-28 20:35 UTC
Labels: xls

**Comment by ajdamico** [comment] 2018-04-28 21:06
thanks so much!  i really appreciate your time and apologies if i did something dumb

**Comment by jennybc** [comment] 2018-04-28 21:33
Ha! No I managed to confuse myself at first as well. I am switching between versions a lot right now.

The fact that this is fixed in dev will only help people who are in a position to build packages with compiled code. Hence the prospect of a patch release to get the libxls fixes out there sooner rather than later.

**Comment by ajdamico** [comment] 2018-04-28 22:25
you are awesome
