### ISSUE TITLE
Refresh cell-specification docs

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/readxl#600] opened 2020-01-21 16:39 UTC
* [ ] Proofread title, description, and parameters 
* [ ] Proofread comments in examples 
* [ ] Ensure comment headings used to divide into scannable sections 
* [ ] Flag examples that seem overly complex for further review 
* [ ] Review size of example outputs to ensure that you can easily see important rows and cols. 
* [ ] Datasets should always be tibbles to avoid use of `as_tibble()` distracting from the main point

**Comment by jennybc** [comment] 2020-01-21 19:02
Doc in question:

https://readxl.tidyverse.org/reference/cell-specification.html

I note that the very best docs for this are in the vignette re: Sheet Geometry:

https://readxl.tidyverse.org/articles/sheet-geometry.html

so that should at least get linked.

It's also possible that some clever work with markdown tables could really enhance this doc or vignette, i.e. instead of using a screenshot to show the Excel sheet we are reading from.

**Comment by heathyates** [comment] 2020-05-08 21:09
Hi @jennybc 

This looks like a good place to get started with readxl. Is this issue still open? Is your link to sheet-geometry kind of a standard you would like to see applied to the first link? 

Thanks, 
Heath

**Comment by jennybc** [comment] 2020-05-11 15:26
Oops, it looks like this actually got done at tidyverse dev day, but the PR did not get linked to this issue:

Closed by #603

**Closed by jennybc** 2020-05-11 15:26 UTC
Labels: documentation, tidy-dev-day :nerd_face:

**Comment by heathyates** [comment] 2020-05-11 15:32
Thanks @jennybc. I am interested in getting started in open source and readxl. Do you have any open issue(s) you would recommend as starters? Thanks kindly in advance.

**Comment by jennybc** [comment] 2020-05-11 15:57
Hmmm, I just took a quick look through the issues and I don't see any that are obviously very approachable for a newcomer and/or that won't require my attention. readxl is a somewhat tough package to focus on because the vast majority of the package is in C/C++ and it is very mature.

If you really want to focus on readxl, then "watch" the repo on GitHub and start listening to the conversation. Try to replicate the problems people see, which will often give you a reason to join the conversation. Either because you can replicate it (in which case, can you make the reprex simpler?) or you can't (which is also interesting). Are there issues that really need a reprex but don't have one? Can you come up with one? All of that is incredibly valuable to a maintainer and helps cultivate your expertise.

A related package that is much more "active" and is pure R is googlesheets4, in case you want to watch that too.

**Comment by heathyates** [comment] 2020-05-11 16:46
Hi @jennybc 

I do love your work on readxl and the package, but for now, I may watch the conversation readxl  as suggested by looking to roll up my sleeves on something else for starters.  

My goal is to start small and simple and then see where that can lead me. In the context of your advice on reproducing issues an [reprex](https://github.com/tidyverse/reprex), do you have any good starter issues with googlesheets4? I think it is a good idea to look into that package. Happy to move ahead in the spirit you have outlined. 

Also, just out of curiosity, when you use C/C++ with readxl, are you using Rcpp? Also, as a R developer, how much pure R do you code in versus optimizing with C/C++?  

Thank you kindly in advance again for your comments and mentoring! Once I have your answers here, happy to try to put that in practice and leave this issue closed. Thanks for your patience. 😁

**Comment by jennybc** [comment] 2020-05-11 17:03
> Also, just out of curiosity, when you use C/C++ with readxl, are you using Rcpp?

This is the kind of info you can look up for yourself in DESCRIPTION and by perusing a package's source code. Given your goals, reading a lot of package source, learning to navigate packages, and learning to search GitHub are great skills to cultivate.

https://github.com/tidyverse/readxl/blob/master/DESCRIPTION#L59 

> Also, as a R developer, how much pure R do you code in versus optimizing with C/C++?

Personally mostly R. For my portfolio, this package is an exception. But across the tidyverse/r-lib, there is an awful lot of C and C++.
