### ISSUE TITLE
does convert dates correctly in the ranges of 1/1/1900 to 2/27/1900

### ISSUE THREAD

**Issue by wjcgh** [tidyverse/readxl#148] opened 2015-12-01 18:21 UTC
Because Excel replicated the Lotus 1-2-3 2/29/1900 bug, there is an off-by-one day conversion error for dates in the ranges of 1/1/1900 to 2/28/1900, which are converted to 12/31/1899 to 2/27/1900. I attached a test file for inclusion in your date test case.
[testdate.xlsx](https://github.com/hadley/readxl/files/48883/testdate.xlsx)

**Comment by jennybc** [comment] 2017-03-11 00:19
Duplicate of #264

**Closed by jennybc** 2017-03-11 00:19 UTC
Labels: datetime
