### ISSUE TITLE
garbled columns in xls

### ISSUE THREAD

**Issue by daxiagithub** [tidyverse/readxl#128] opened 2015-09-11 17:11 UTC
Hi,

First of all, thanks for writing the readxl package, which is very simple and useful!

However, when I use the read_excel function, I got very different behaviors in Windows vs Linux.  Attached is a test .xls file.  (Sorry, I don't know how to attach a file.  The file has been sent to Hadley Wickham already).

Here is the output from Widnows (Win 7, I'm running R 3.2.2 with readxl 0.1.0).  Everything is fine.

> read_excel("test.xls", skip=9)

Source: local data frame [13 x 12]

  Cell count total Type  Compound Solvent Unit  Dose  X1  X2  X3  X4  X5  X6
1                NA  NA BACKGROUND      NA  NA    NA  0  0  0  0  0  0
2            50000    L    CONTROL      NA  NA    NA 157 175 168 162 157 149
3            50000    L        xx    DMSO  µM 3e-04 156 148  NA  NA  NA  NA
4            50000    L        xx    DMSO  µM 1e-03 161 159  NA  NA  NA  NA
5            50000    L        xx    DMSO  µM 3e-03 154 165  NA  NA  NA  NA
6            50000    L        xx    DMSO  µM 1e-02 152 154  NA  NA  NA  NA
7            50000    L        xx    DMSO  µM 3e-02 156 141  NA  NA  NA  NA
8            50000    L        xx    DMSO  µM 1e-01 122 111  NA  NA  NA  NA
9            50000    L        xx    DMSO  µM 3e-01  51  42  NA  NA  NA  NA
10            50000    L        xx    DMSO  µM 1e+00  19  16  NA  NA  NA  NA
11            50000    L        xx    DMSO  µM 3e+00  3  6  NA  NA  NA  NA
12            50000    L        xx    DMSO  µM 1e+01  10  8  NA  NA  NA  NA
13            50000    L        yy    DMSO  µM 1e+02  1  3  1  1  5  1

> read_excel("test.xls", col_names = F)

Source: local data frame [23 x 12]

```
     X1              X2      X3      X4  X5  X6 X7 X8 X9 X10 X11 X12
```

1    EXP. DATE VT 0    42024.000000      NA      NA  NA  NA NA NA NA  NA  NA  NA
2    EVAL. DAY VT 8    42032.000000      NA      NA  NA  NA NA NA NA  NA  NA  NA
3                NA              NA      NA      NA  NA  NA NA NA NA  NA  NA  NA
4              DYE  Image analysis      NA      NA  NA  NA NA NA NA  NA  NA  NA
5            READER CellInsight NXT      NA      NA  NA  NA NA NA NA  NA  NA  NA
6  CELL COUNT TOTAL        cells/mL      NA      NA  NA  NA NA NA NA  NA  NA  NA
7                NA              NA      NA      NA  NA  NA NA NA NA  NA  NA  NA
8                NA              NA      NA      NA  NA  NA NA NA NA  NA  NA  NA
9                NA              NA      NA      NA  NA  NA NA NA NA  NA  NA  NA
10 Cell count total            Type Compound Solvent Unit Dose X1 X2 X3  X4  X5  X6

..              ...            ...      ...    ...  ...  ... .. .. .. ... ... ...

However, when I switch to Linux (RHEL 6.4, R 3.2.0, readxls 0.1.0), here is the output:

> read_excel("test.xls", skip=9) 
Source: local data frame [13 x 8] 

.1  .2  .3 
1    NA    NA  0  0 
2  50000    NA 157 175 
3  50000 3e-04 156 148 
4  50000 1e-03 161 159 
5  50000 3e-03 154 165 
6  50000 1e-02 152 154 
7  50000 3e-02 156 141 
8  50000 1e-01 122 111 
9  50000 3e-01  51  42 
10 50000 1e+00  19  16 
11 50000 3e+00  3  6 
12 50000 1e+01  10  8 
13 50000 1e+02  1  3 
Variables not shown: structure(c(" 0", "168", " NA", " NA", " NA", " NA", " NA", (dbl), structure(c(" 0", "162", " NA", " NA", " NA", " NA", " NA", (dbl), structure(c(" 0", "157", " NA", " NA", " NA", " NA", " NA", (dbl), 
structure(c(" 0", "149", " NA", " NA", " NA", " NA", " NA", (dbl) 

> read_excel("test.xls", col_names = F) 
Source: local data frame [23 x 9] 

X1        X2 X6 X7 X8 X9 X10 X11 X12 
1  NA 2015-01-20 NA NA NA NA  NA  NA  NA 
2  NA 2015-01-28 NA NA NA NA  NA  NA  NA 
3  NA      <NA> NA NA NA NA  NA  NA  NA 
4  NA      <NA> NA NA NA NA  NA  NA  NA 
5  NA      <NA> NA NA NA NA  NA  NA  NA 
6  NA      <NA> NA NA NA NA  NA  NA  NA 
7  NA      <NA> NA NA NA NA  NA  NA  NA 
8  NA      <NA> NA NA NA NA  NA  NA  NA 
9  NA      <NA> NA NA NA NA  NA  NA  NA 
10 NA      <NA> NA NA NA NA  NA  NA  NA 
.. ..        ... .. .. .. .. ... ... ...

Could you please explain what happened here? 

Thank you very much!

Tao

**Comment by daxiagithub** [comment] 2015-09-11 19:08
I put the test file here.

https://drive.google.com/file/d/0B2sRq88YYSHwX2h3TXRJbTRLaUk/view?usp=sharing

**Comment by jennybc** [comment] 2017-02-24 13:58
I can't reproduce this on Mac, but acknowledge the original report was about different behaviour on RHEL 6.4 vs. Windows. So this doesn't really prove anything.

``` r
library(readxl)
df <- read_excel("iss/iss128.xls", skip = 9, col_names = TRUE)
df
#> # A tibble: 13 × 12
#>    `Cell count total`  Type   Compound Solvent  Unit  Dose    X1    X2
#>                 <dbl> <chr>      <chr>   <chr> <chr> <dbl> <dbl> <dbl>
#> 1                  NA  <NA> BACKGROUND    <NA>  <NA>    NA     0     0
#> 2               50000     L    CONTROL    <NA>  <NA>    NA   157   175
#> 3               50000     L         xx    DMSO    µM 3e-04   156   148
#> 4               50000     L         xx    DMSO    µM 1e-03   161   159
#> 5               50000     L         xx    DMSO    µM 3e-03   154   165
#> 6               50000     L         xx    DMSO    µM 1e-02   152   154
#> 7               50000     L         xx    DMSO    µM 3e-02   156   141
#> 8               50000     L         xx    DMSO    µM 1e-01   122   111
#> 9               50000     L         xx    DMSO    µM 3e-01    51    42
#> 10              50000     L         xx    DMSO    µM 1e+00    19    16
#> 11              50000     L         xx    DMSO    µM 3e+00     3     6
#> 12              50000     L         xx    DMSO    µM 1e+01    10     8
#> 13              50000     L         yy    DMSO    µM 1e+02     1     3
#> # ... with 4 more variables: X3 <dbl>, X4 <dbl>, X5 <dbl>, X6 <dbl>
```

@daxiagithub Will you install readxl from a pull request and see if the problem persists on RedHat for you?

``` r
devtools::install_github("tidyverse/readxl#271")
```

**Comment by hadley** [comment] 2017-03-09 17:46
Given that there's been no feedback and it works on your computer, I'd say it's ok to close this one.

**Closed** 2017-03-09 17:48 UTC
Labels: bug, xls
