### ISSUE TITLE
Lost column

### ISSUE THREAD

**Issue by kablag** [tidyverse/readxl#152] opened 2015-12-18 15:48 UTC
I have strange bug.
Third party software generates xls files. I try to get data from them with such code:

``` r
read_excel("test.xls",
                    sheet = "Multicomponent Data",
                    skip = 7) %>% colnames()
[1] "Well"  "Cycle" "FAM"   "ROX"
```

and got only 4 columns, but data sheet has 5 columns (last column is lost).

When I open this file in Excel 2013 (it views all columns) and save with the new name (test2.xls) everything work fine:

``` r
read_excel("test2.xls",
                    sheet = "Multicomponent Data",
                    skip = 7) %>% colnames()
[1] "Well"  "Cycle" "FAM"   "ROX"   "VIC"
```

OS is Windows 7/10.

[test_xls.zip](https://github.com/hadley/readxl/files/66796/test_xls.zip)

**Comment by jamesclarence** [comment] 2016-03-10 17:57
I think I'm having the same issue with a third party software that generates xls files, too. @kablag When you open the .xls file in Excel, do you get `[Compatibility Mode]` next to the file name at the top, something like `"test [Compatibility Mode] - Excel"`?

**Comment by kablag** [comment] 2016-03-10 18:27
@jamesclarence I got this message  `"test [Compatibility Mode] - Excel"`, but Excel always writes this when you open xls instead of xlsx.

**Comment by jamesclarence** [comment] 2016-03-14 00:15
Gotcha. Either way, I have had to "save as" the third party generated Excel file before using `read_excel` in order to read all the columns into R.

**Comment by jennybc** [comment] 2017-02-24 11:37
Suspect duplicate of #128. Thanks for the example sheet!

**Comment by jennybc** [comment] 2017-02-24 15:46
I don't think this is a duplicate after all, but I do see what's going on here.

**Closed** 2017-02-25 15:51 UTC
Labels: xls
