### ISSUE TITLE
time conversion bug report

### ISSUE THREAD

**Issue by klausbh** [tidyverse/readxl#167] opened 2016-04-25 17:30 UTC
Hi there,

I just wanted to share that under some circumstances read_excel() does not process "excel time" correctly after all. I suspect the problem has something to do with rounding of sub-second time intervals. In Excel, formatting the number 21916.4548263889 as h:mm:ss yields "10:54:57", whereas read_excel gives "10:54:58 UTC". For what it is worth, chron(.4548263889) agrees with Excel.

-Klaus

[problem.xlsx](https://github.com/hadley/readxl/files/235033/problem.xlsx)

**Comment by hadley** [comment] 2017-02-09 14:11
Duplicate of #187

**Closed by hadley** 2017-02-09 14:11 UTC
Labels: datetime
