### ISSUE TITLE
Difference of one day.

### ISSUE THREAD

**Issue by stla** [tidyverse/readxl#264] opened 2017-02-13 17:43 UTC
Hello, 

I create a `xlsx` file with a "Time" formatting:
```
library(openxlsx)
dat <- data.frame(A=c(1, 1.5, 1.8))
wb <- createWorkbook()
addWorksheet(wb=wb, sheetName = "Sheet1")
sty <- createStyle(numFmt = "h:mm AM/PM")
addStyle(wb, sheet=1, style=sty, rows=2:4, cols=1)
writeData(wb, sheet=1, dat)
saveWorkbook(wb, "test02.xlsx", overwrite = TRUE) 
```

In Excel:

![capture](https://cloud.githubusercontent.com/assets/4466543/22895279/2cd3f69e-f21c-11e6-9305-083e5c4c31ee.PNG)

But:

```
> readxl::read_excel("test02.xlsx", sheet=1)
                    A
1 1899-12-31 00:00:00
2 1899-12-31 12:00:00
3 1899-12-31 19:12:00
```

**Comment by nacnudus** [comment] 2017-02-13 19:18
This is because of Excel's leap-year bug.  Excel addresses it by printing `1/01/1900`, which it can do because it also uses `29/02/1900`.  In R, `29/02/1900` is impossible.

I'd be interested to see how you handle this in `readxl`.  In `tidyxl` I give the user a warning.

**Comment by hadley** [comment] 2017-02-13 19:29
Duplicate of #148

**Comment by jennybc** [comment] 2017-03-11 00:19
Yes duplicate of #148, which I am closing ... but note that it contains an example xlsx.

**Comment by jennybc** [comment] 2017-03-11 15:48
Good description of how ssf (format code handler for SheetJS) deals with this:

https://github.com/SheetJS/ssf/blob/master/ssf.md#parsing-date-and-time-codes

**Closed** 2017-03-13 18:08 UTC
Labels: bug, datetime
