### ISSUE TITLE
Readxl reading numeric-formatted data as Dates, generating loads of warnings when type specified explicitly

### ISSUE THREAD

**Issue by misea** [tidyverse/readxl#631] opened 2020-09-20 21:39 UTC
In reading an XLSX file provided by HUD, readxl v 1.3.1 is loading dates instead of numeric values, despite the numbers appearing as floating point when opened in Excel. They do not appear to be date formatted.

I have attached the first 2 rows of the file 
[readxl_test.xlsx](https://github.com/tidyverse/readxl/files/5252690/readxl_test.xlsx)

```{r}
# The following loads dates
readxl::read_xlsx("readxl_test.xlsx")

# The following generates 4 warnings per row
readxl::read_xlsx("readxl_test.xlsx", col_types = c("text", "text", "numeric", "numeric", "numeric", "numeric"))
```
Replicates on local Mac and an RStudio server running Debian. The problem would not be so bad except that I made the mistake of loading the complete ZIP/COUNTY crosswalk file available from HUD: https://www.huduser.gov/portal/datasets/usps_crosswalk.html on RStudio server Pro (1.3.1073-1) in an Rmd file that was showing warnings. The attempt to spew tens of thousands of warnings overwhelmed my browser & I had to close the window.

**Comment by hidekoji** [comment] 2020-10-06 16:24
I have the same issue. The issue seems related to Cell format "Negative numbers format".  For my case, when I pick 1234.10 in red color or (1234.10) in red color ended up with POSIXct column instead of numeric column.

![image](https://user-images.githubusercontent.com/230637/95229458-73e82200-07b5-11eb-8845-53a475d6f565.png)

**Comment by mburghart-qualitrol** [comment] 2022-01-06 22:30
I think this may be due to the numbering format code containing a character which would be interpreted as part of a date-time numbering format.  For example the format code `0;[Red]0` contains the letter "d", and this seems to trigger the column to be mis-identified as a date-time instead of numeric.  If you change the format code to `0;[Blue]0`, the behavior changes to the expected. (Is the parsing of the numbering format to determine if it is a date-time too simplistic?)

**Comment by mburghart-qualitrol** [comment] 2022-01-06 23:14
Here is an example spreadsheet which illustrates the issue with mis-identifying numeric columns as date-time columns.  The first column are integers with numbering format "0".  The subsequent columns are the same values using numbering formats with various colors. For the _red_ column the numbering format is `0;[Red]-0`.  This was then read using read_xlsx.

```
> packageVersion( "readxl" )
[1] ‘1.3.1’
> df = readxl::read_xlsx( ex_fp )
Warning messages:
1: In read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  :
  NA inserted for impossible 1900-02-29 datetime
2: In read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  :
  NA inserted for impossible 1900-02-29 datetime
3: In read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  :
  NA inserted for impossible 1900-02-29 datetime
4: In read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  :
  NA inserted for impossible 1900-02-29 datetime
5: In read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  :
  NA inserted for impossible 1900-02-29 datetime
> str( df )
tibble [5 x 9] (S3: tbl_df/tbl/data.frame)
 $ integer: num [1:5] -2 -1 0 1 2
 $ red    : POSIXct[1:5], format: NA "1899-12-30" ...
 $ green  : num [1:5] -2 -1 0 1 2
 $ blue   : num [1:5] -2 -1 0 1 2
 $ cyan   : POSIXct[1:5], format: NA "1899-12-30" ...
 $ magenta: POSIXct[1:5], format: NA "1899-12-30" ...
 $ yellow : POSIXct[1:5], format: NA "1899-12-30" ...
 $ black  : num [1:5] -2 -1 0 1 2
 $ white  : POSIXct[1:5], format: NA "1899-12-30" ...
>
```

The columns for colors "Red", "Cyan", "Magenta", "Yellow" and "White" were incorrectly identified as date-time.
The columns for colors "Green", "Blue", and "Black" were correctly identifies as numeric.

[numfmt_colors_example.xlsx](https://github.com/tidyverse/readxl/files/7825234/numfmt_colors_example.xlsx)

**Comment by mburghart-qualitrol** [comment] 2022-01-07 00:00
I see where parsing the numeric format code is done for identifying date-time formats.  Interesting comments in the function `isDateFormat`.

excerpt from `src/ColSpec.h`: 

```
inline bool isDateFormat(std::string x) {
  // TO FIX? So far no bug reports due to this.
  // Logic below is too simple. For example, it deems this format string a date:
  // "$"#,##0_);[Red]\("$"#,##0\)
  // because of the `d` in `[Red]`
  //
  // Ideally this can wait until we are using something like
  // https://github.com/WizardMac/TimeFormatStrings
  // which presumably offers fancier ways to analyze format codes.
  for (size_t i = 0; i < x.size(); ++i) {
    switch (x[i]) {
    case 'd':
    case 'D':
    case 'm': // 'mm' for minutes
    case 'M':
    case 'y':
    case 'Y':
    case 'h': // 'hh'
    case 'H':
    case 's': // 'ss'
    case 'S':
      return true;
    default:
      break;
    }
  }

  return false;
}
```

**Comment by jennybc** [comment] 2022-01-07 07:08
This is basically a duplicate of #388. It is a long-standing, known issue. I am just starting to work on readxl again after a long hiatus.

**Comment by mitchbur** [comment] 2022-01-07 19:36
[switched from mburghart-qualitrolcorp to my personal github account]  I am willing to help with resolving issue #388; I some ideas on how to rework `isDateFormat`.  Please let me know how I can get involved with the project.

**Comment by jennybc** [comment] 2022-01-07 20:25
Pull requests are welcome. For the record, there already is one related to this issue (#559). Basically I haven't done major work on readxl for a while, so have not deeply engaged with this addressing this issue myself or with evaluating that PR.

Ideally, we'd find that there is some external library that has tackled the problem head-on, that we could rely on. Or suitably licensed code in another Excel-reading library that solve this common problem. I just haven't re-researched all of that since I wrote the comments you see in the source.

I have some minor and major housekeeping tasks that are a higher priority as I "wake things up" again here. But I'm definitely interested fixing this!

**Comment by jennybc** [comment] 2022-03-20 17:23
I'm closing in favour of #388. The two issues will be linked so the discussion here will still be considered.

**Closed by jennybc** 2022-03-20 17:23 UTC
