### ISSUE TITLE
col_names and col_types both explicitly set, but read_excel throws the "need one for each column" error

### ISSUE THREAD

**Issue by bbritten** [tidyverse/readxl#137] opened 2015-10-14 18:26 UTC
I have a data set that I'm trying to read, but can't seem to get past this error. Here's my workflow:

``` r
file = "C:/path/to/directory/file.xlsx"
sheet_names <- readxl::excel_sheets(file)
sheet_index <- stringr::str_detect(sheet_names, "^Voice") %>% which() - 1 #index starts at 0

col_names <- .Call("readxl_xlsx_col_names", PACKAGE = "readxl", file, sheet_index, 0)
blank <- sum(col_names == "")
col_names[col_names == ""] <- paste("var", 1:blank, sep = "_")

n <- length(col_names)
col_types <- rep("text", n)

dat <- readxl::read_excel(file, sheet = sheet_index, col_types == col_types, col_names == col_names, skip = 0)
Error: Need one name and type for each column 
```

Here is what col_names and col_types look like:

``` r
> col_names
 [1] "Type"                 "Item"                 "Conn Date Time (UTC)" "CT"                   "Originating Number"   "Terminating Number"   "DIALED"               "FORWARDED"            "TRANSLATED"          
[10] "ORIG_ORIG"            "Seizure Time"         "ET"                   "IMEI"                 "IMSI"                 "Feature"              "MAKE"                 "MODEL"                "Cell Location"       
[19] "Latitude"             "Longitude"            "Google Map Link"      "var_1"                "var_2"                "var_3"                "var_4"                "var_5"                "var_6"               
[28] "var_7"                "var_8"                "var_9"                "var_10"               "var_11"               "var_12"               "var_13"               "var_14"               "var_15"              
[37] "var_16"               "var_17"               "var_18"               "var_19"               "var_20"               "var_21"               "var_22"               "var_23"               "var_24"              
[46] "var_25"              
> col_types
 [1] "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text"
[33] "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text" "text"
```

I thought the missing column names at the end was causing a problem, but that's not it. Then I thought it might be the spacing in the variable names, but that's not it either. So I'm at a total loss as to what to do given that I've explicitly named each variable and declared a type for each as well.

**Comment by masalmon** [comment] 2016-04-07 16:33
The issue is old but who knows... I faced a similar issue but my Excel file had "#" in the column names, so in such a case it might be worth checking that there are no special characters in the file.

**Comment by jennybc** [comment] 2017-01-29 07:55
I am closing in on these issues but specific example sheets are always helpful for making sure and writing tests. Can either of you share one that triggered this specific message?

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by masalmon** [comment] 2017-01-29 07:59
@jennybc IIRC it's one I had sent privately to Rich for your project 😊

**Comment by jennybc** [comment] 2017-02-10 07:34
@bbritten Although I have no way to check w/o a reprex, I suspect you have cells trailing to the right of your data that also have a format applied. Such cells are ignored as of https://github.com/tidyverse/readxl/commit/c6e0f8f2c06b5b7923e6eeffadbe59b7984ea64d and I suspect you would not get this error now. Closing as a presumed duplicate of #81.

**Closed by jennybc** 2017-02-10 07:34 UTC
Labels: bug
