### ISSUE TITLE
Issue with reading xls file

### ISSUE THREAD

**Issue by lz1nwm** [tidyverse/readxl#190] opened 2016-07-07 10:29 UTC
``` R
library(readxl)

path = "http://www.nsi.bg/sites/default/files/files/data/timeseries/dTrade_2.1.1_mS_en.xls"

download.file(path, destfile = "dTrade_2.1.1_mS_en.xls", mode="wb")

dt_sheet_1 <- read_excel('dTrade_2.1.1_mS_en.xls', sheet = 1, col_names = F, skip = 6)
dt_sheet_3 <- read_excel('dTrade_2.1.1_mS_en.xls', sheet = 3, col_names = F, skip = 6)
```

The problem with the above file is that in some sheets `readxl` doesn't read correctly the first column and fills it with strange numbers. Check sheet 3 in the file and data frame`dt_sheet_3`. The same file could be read correctly with `XLConnect`.

**Comment by KarinaMarks** [comment] 2016-07-07 16:30
Looks similar to the issue I have raised #189 , are you also operating on Centos?

**Comment by lz1nwm** [comment] 2016-07-08 07:19
My OS is Win7 x64 SP1. Below is the session info:

```R
> devtools::session_info()
Session info ---------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       RStudio (0.99.902)          
 language (EN)                        
 collate  English_United States.1252  
 tz       Europe/Helsinki             
 date     2016-07-08                  

Packages -------------------------------------------------------------------------------------------------------------------------
 package   * version date       source        
 devtools    1.12.0  2016-06-24 CRAN (R 3.3.1)
 digest      0.6.9   2016-01-08 CRAN (R 3.3.1)
 memoise     1.0.0   2016-01-29 CRAN (R 3.3.1)
 Rcpp        0.12.5  2016-05-14 CRAN (R 3.3.1)
 readxl    * 0.1.1   2016-03-28 CRAN (R 3.3.0)
 rsconnect   0.4.3   2016-05-02 CRAN (R 3.3.1)
 withr       1.0.2   2016-06-20 CRAN (R 3.3.0)
```

**Comment by jennybc** [comment] 2017-02-05 00:36
Thanks for providing a link to a publicly available file @lz1nwm! However I can't reproduce this.

I need you to show me what exactly goes wrong, i.e. what you mean by "fills it with strange numbers". Can you create a version of your reprex that shows me some printed output? The reprex package linked below might help.

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by lz1nwm** [comment] 2017-02-06 09:13
@jennybc see the code below and please check `sheet_1_readxl$X1` and `sheet_1_XLConnect$Col1` (the latter is the correct output while the former shows "strange numbers"). 


``` r
library(readxl)
library(reprex)
library(XLConnect)

path = "http://www.nsi.bg/sites/default/files/files/data/timeseries/dTrade_2.1.1_mS_en.xls"

download.file(path, destfile = "dTrade_2.1.1_mS_en.xls", mode="wb")

sheet_1_readxl <- read_excel('dTrade_2.1.1_mS_en.xls', sheet = 1, col_names = F, skip = 6)
head(sheet_1_readxl)
#>       X1   X2     X3     X4     X5     X6     X7     X8     X9    X10
#> 1 172.22    G 101.29  99.18 112.59 112.97 110.55 111.78 127.47 128.35
#> 2 178.87  G45 122.47 120.39 134.86 145.47 144.92 149.11 150.68 138.17
#> 3 186.19  G46  98.97  96.93 110.89 109.30 105.61 105.88 123.48 125.42
#> 4 191.33 <NA>     NA     NA     NA     NA     NA     NA     NA     NA
#> 5 195.35 G462 104.16  92.86 113.18 102.63  83.97  77.80 199.01 263.17
#> 6 213.83 G463  88.92  85.69  88.37  93.51  95.80  97.43 105.51 105.34
#>      X11    X12    X13    X14
#> 1 122.59 123.71 118.53 114.29
#> 2 158.29 184.53 189.12 166.61
#> 3 117.04 117.08 112.16 102.14
#> 4     NA     NA     NA     NA
#> 5 178.53 192.67 201.17 139.37
#> 6  95.31  88.23  81.37  85.02

wb <- loadWorkbook('dTrade_2.1.1_mS_en.xls')
sheet_1_XLConnect <- readWorksheet(wb, sheet = 1, header = F, startRow = 7)
head(sheet_1_XLConnect)
#>                                                                      Col1
#> 1                                                                   Total
#> 2 Wholesale and retail trade and repair of motor vehicles and motorcycles
#> 3               Wholesale trade, except of motor vehicles and motorcycles
#> 4                                                               of which:
#> 5              Wholesale of  agricultural raw materials  and live animals
#> 6                               Wholesale of  food, beverages and tobacco
#>   Col2   Col3   Col4   Col5   Col6   Col7   Col8   Col9  Col10  Col11
#> 1    G 101.29  99.18 112.59 112.97 110.55 111.78 127.47 128.35 122.59
#> 2  G45 122.47 120.39 134.86 145.47 144.92 149.11 150.68 138.17 158.29
#> 3  G46  98.97  96.93 110.89 109.30 105.61 105.88 123.48 125.42 117.04
#> 4 <NA>     NA     NA     NA     NA     NA     NA     NA     NA     NA
#> 5 G462 104.16  92.86 113.18 102.63  83.97  77.80 199.01 263.17 178.53
#> 6 G463  88.92  85.69  88.37  93.51  95.80  97.43 105.51 105.34  95.31
#>    Col12  Col13  Col14
#> 1 123.71 118.53 114.29
#> 2 184.53 189.12 166.61
#> 3 117.08 112.16 102.14
#> 4     NA     NA     NA
#> 5 192.67 201.17 139.37
#> 6  88.23  81.37  85.02
```

**Comment by jennybc** [comment] 2017-02-06 16:36
Thanks @lz1nwm! I haven't digested the above yet but quickly ...

Are you using the current development version of readxl or the CRAN version? I'd really love to see your results with the *development* version installed from GitHub.

**Comment by lz1nwm** [comment] 2017-02-07 11:54
@jennybc I tried with the development version and unfortunately result is almost the same as above:

``` r
library(readxl)
library(reprex)
library(XLConnect)

path = "http://www.nsi.bg/sites/default/files/files/data/timeseries/dTrade_2.1.1_mS_en.xls"

download.file(path, destfile = "dTrade_2.1.1_mS_en.xls", mode="wb")

sheet_1_readxl <- read_excel('dTrade_2.1.1_mS_en.xls', sheet = 1, col_names = F, skip = 6)
head(sheet_1_readxl)
#> # A tibble: 6 Ã— 14
#>       X1    X2     X3     X4     X5     X6     X7     X8     X9    X10
#>    <dbl> <chr>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>
#> 1 172.22     G 101.29  99.18 112.59 112.97 110.55 111.78 127.47 128.35
#> 2 178.87   G45 122.47 120.39 134.86 145.47 144.92 149.11 150.68 138.17
#> 3 186.19   G46  98.97  96.93 110.89 109.30 105.61 105.88 123.48 125.42
#> 4 191.33  <NA>     NA     NA     NA     NA     NA     NA     NA     NA
#> 5 195.35  G462 104.16  92.86 113.18 102.63  83.97  77.80 199.01 263.17
#> 6 213.83  G463  88.92  85.69  88.37  93.51  95.80  97.43 105.51 105.34
#> # ... with 4 more variables: X11 <dbl>, X12 <dbl>, X13 <dbl>, X14 <dbl>

wb <- loadWorkbook('dTrade_2.1.1_mS_en.xls')
sheet_1_XLConnect <- readWorksheet(wb, sheet = 1, header = F, startRow = 7)
head(sheet_1_XLConnect)
#>                                                                      Col1
#> 1                                                                   Total
#> 2 Wholesale and retail trade and repair of motor vehicles and motorcycles
#> 3               Wholesale trade, except of motor vehicles and motorcycles
#> 4                                                               of which:
#> 5              Wholesale of  agricultural raw materials  and live animals
#> 6                               Wholesale of  food, beverages and tobacco
#>   Col2   Col3   Col4   Col5   Col6   Col7   Col8   Col9  Col10  Col11
#> 1    G 101.29  99.18 112.59 112.97 110.55 111.78 127.47 128.35 122.59
#> 2  G45 122.47 120.39 134.86 145.47 144.92 149.11 150.68 138.17 158.29
#> 3  G46  98.97  96.93 110.89 109.30 105.61 105.88 123.48 125.42 117.04
#> 4 <NA>     NA     NA     NA     NA     NA     NA     NA     NA     NA
#> 5 G462 104.16  92.86 113.18 102.63  83.97  77.80 199.01 263.17 178.53
#> 6 G463  88.92  85.69  88.37  93.51  95.80  97.43 105.51 105.34  95.31
#>    Col12  Col13  Col14
#> 1 123.71 118.53 114.29
#> 2 184.53 189.12 166.61
#> 3 117.08 112.16 102.14
#> 4     NA     NA     NA
#> 5 192.67 201.17 139.37
#> 6  88.23  81.37  85.02
```


Here is my current session info if it could help:

``` R
> devtools::session_info()
Session info ------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, mingw32             
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  English_United States.1252  
 tz       Europe/Helsinki             
 date     2017-02-07                  

Packages ----------------------------------------------------------------------------------------------------------------------
 package       * version    date       source                           
 assertthat      0.1        2013-12-06 CRAN (R 3.3.2)                   
 curl            2.3        2016-11-24 CRAN (R 3.3.2)                   
 devtools        1.12.0     2016-06-24 CRAN (R 3.3.2)                   
 digest          0.6.12     2017-01-27 CRAN (R 3.3.2)                   
 git2r           0.18.0     2017-01-01 CRAN (R 3.3.2)                   
 httr            1.2.1      2016-07-03 CRAN (R 3.3.2)                   
 knitr           1.15.1     2016-11-22 CRAN (R 3.3.2)                   
 memoise         1.0.0      2016-01-29 CRAN (R 3.3.2)                   
 R6              2.2.0      2016-10-05 CRAN (R 3.3.2)                   
 Rcpp            0.12.9     2017-01-14 CRAN (R 3.3.2)                   
 readxl        * 0.1.1.9000 2017-02-07 Github (tidyverse/readxl@c6e0f8f)
 reprex        * 0.1.1      2017-01-13 CRAN (R 3.3.2)                   
 rJava           0.9-8      2016-01-07 CRAN (R 3.3.0)                   
 tibble          1.2        2016-08-26 CRAN (R 3.3.1)                   
 withr           1.0.2      2016-06-20 CRAN (R 3.3.2)                   
 XLConnect     * 0.2-12     2016-06-24 CRAN (R 3.3.1)                   
 XLConnectJars * 0.2-12     2016-06-24 CRAN (R 3.3.1) 

```

**Comment by jennybc** [comment] 2017-02-07 15:54
@lz1nwm OK got it. I didn't have any reason to think your specific problem was fixed but it was worth checking. I am slowly working my way to xls-specific problems.

**Comment by jennybc** [comment] 2017-02-24 16:08
Possible duplicate of #128.

**Comment by jennybc** [comment] 2017-03-19 06:02
No, not a duplicate of #128.

**Comment by jennybc** [comment] 2017-03-20 18:37
This is definitely a bug in libxls and at a deeper level than I'm currently willing or able to solve.

I can see that it travels through all the cells as it should. In particular, it loads the correct strings for the first column of the first sheet from the above reprex.

But THEN it travels through the first column only two more times and by the 3rd trip through, the cell type has somehow become numeric, resulting in the garbage numbers you see above.

I'm going to close this, as I'm not in a position to fix it. If you have lots of sheets like this and/or can say specifically which s/w wrote it (I seriously doubt it was Excel), you could open a new issue and maybe we could elevate it to a bug report on libxls itself.

**Closed by jennybc** 2017-03-20 18:37 UTC
Labels: bug, xls

**Comment by reviewher** [comment] 2017-03-21 00:36
@jennybc it appears to be a file from Excel 2010.  This should be a pretty simple bug fix for the libxls devs.  I'm not sure how to report a bug to them (do they have a GitHub?)

The file has records corresponding to charts on every sheet.  A cursory glance of the sheets reveal no such charts, but the file has a nested chart stream within each worksheet stream.  The chart stream happens to store data in the first column, which is why you see the weird data.  The simplest fix in libxls is to keep a depth counter, incremented whenever a [`BOF` record](https://msdn.microsoft.com/en-us/library/dd906793.aspx) is encountered and decremented whenever an [`EOF` record](https://msdn.microsoft.com/en-us/library/dd904865.aspx) is encountered, and disregard any cell data if the depth exceeds 1.  Doing that, the weird data is skipped.

**Comment by jennybc** [comment] 2017-03-21 03:17
@reviewher Interesting! Thanks for taking a look.

libxls is maintained only on sourceforge. There have been a couple of commits in 2017, but in general it appears to be in deep "maintenance mode". Changes are quite rare at this point, so we've made a couple of patches here in in readxl, some of which might make their way into libxls (?). But this one is beyond my level of understanding and interest. If you can file an actionable bug report using this sheet, maybe something would come of it. Here's where to go:

http://libxls.sourceforge.net

https://sourceforge.net/projects/libxls/
