### ISSUE TITLE
Use Excel column names or RC reference as default names in read_excel

### ISSUE THREAD

**Issue by mkoohafkan** [tidyverse/readxl#712] opened 2022-10-13 15:15 UTC
Reading in an excel range with `col_names = FALSE` results in uninformative name creation messages:

```r
d = read_excel(my_book, my_sheet, "A1:C6", col_names = FALSE)

#> New names:
#> • `` -> `...1`
#> • `` -> `...2`
#> • `` -> `...3`
```
Neither the message or the resulting names are helpful or clear. However, it should be simple to derive appropriate default names from the workbook columns and/or RC notation, both of which result in valid names:

- A1:C6 --> "A", "B", "C"
- R1C1:R6C3 --> "C1", "C2", "C3"

You could also generate default row names using this logic.

**Comment by jennybc** [comment] 2023-02-09 00:08
Duplicate of #522

**Closed by jennybc** 2023-02-09 00:08 UTC
