### ISSUE TITLE
¿Error reading data?

### ISSUE THREAD

**Issue by skanskan** [tidyverse/readxl#146] opened 2015-11-04 20:18 UTC
Hello.

I've uploaded this simple excel file.

http://www67.zippyshare.com/v/0PNe04je/file.html

It contains 6 columns and 60 rows.

When I use this command:
data <- read_excel("CoIn.xlsx", sheet=1, col_names=TRUE ,  na="", skip=0)

data contains not only the proper columns but also many others filled with NA

If I read the same excel file with other packages I don't have any issue.

**Comment by jennybc** [comment] 2017-01-31 06:42
Can you please attach the example file to this issue thread? Thanks!

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by jennybc** [comment] 2017-02-05 00:14
Until proven otherwise, I assume this is a duplicate of #162.

**Closed by jennybc** 2017-02-05 00:14 UTC
Labels: reprex
