### ISSUE TITLE
(Feature request) Support for Excel Named Cells, Ranges, and Tables 

### ISSUE THREAD

**Issue by ajit555** [tidyverse/readxl#643] opened 2021-05-15 01:07 UTC
Support for Excel Named Cells, Ranges, and Tables #377
https://github.com/tidyverse/readxl/issues/377

Excel's recommended best practice is to use tables for storing tabular data. It would be useful if we can import the excel table in R.

**Comment by jennybc** [comment] 2021-05-18 17:21
Semi-duplicate of #317 (morally the same wishes)

**Comment by jennybc** [comment] 2022-03-20 05:26
I'm going to close this because #317 captures the basic goal.

**Closed by jennybc** 2022-03-20 05:26 UTC
